#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "DockScrollItemWidget.generated.h"

class UButton;
class UBorder;
class UDockScrollWidget;
class UImage;
class UTextBlock;
class UTexture2D;

USTRUCT(BlueprintType)
struct DEMO2_API FDockScrollItemData
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dock Item")
	FName ItemId = NAME_None;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dock Item")
	FText DisplayName;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dock Item")
	TObjectPtr<UTexture2D> Image = nullptr;
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FDockItemClickedSignature, int32, ItemIndex, FName, ItemId);

/**
 * Base class for a dock item. Blueprint subclasses may provide widgets named
 * SelectButton, ItemImage and ItemName. When they are absent, a complete
 * default item layout is generated by C++.
 */
UCLASS(Blueprintable, BlueprintType)
class DEMO2_API UDockScrollItemWidget : public UUserWidget
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintCallable, Category = "Dock Item")
	void InitializeItem(const FDockScrollItemData& InData, int32 InIndex, UDockScrollWidget* InOwner);

	UFUNCTION(BlueprintCallable, Category = "Dock Item")
	void SetDockScale(float InScale, float LiftAmount, float InOpacity);

	UFUNCTION(BlueprintCallable, Category = "Dock Item")
	void SetDockVisualState(bool bIsHovered, bool bIsSelected, bool bIsCurrent);

	void TickDockVisual(float DeltaTime);

	UFUNCTION(BlueprintCallable, Category = "Dock Item")
	void ActivateItem();

	UFUNCTION(BlueprintPure, Category = "Dock Item")
	int32 GetItemIndex() const { return ItemIndex; }

	UFUNCTION(BlueprintPure, Category = "Dock Item")
	const FDockScrollItemData& GetItemData() const { return ItemData; }

	UPROPERTY(BlueprintAssignable, Category = "Dock Item|Events")
	FDockItemClickedSignature OnItemClicked;

protected:
	virtual void NativeOnInitialized() override;
	virtual void NativeOnMouseEnter(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent) override;
	virtual void NativeOnMouseLeave(const FPointerEvent& InMouseEvent) override;
	virtual FReply NativeOnKeyDown(const FGeometry& InGeometry, const FKeyEvent& InKeyEvent) override;

	UFUNCTION(BlueprintImplementableEvent, Category = "Dock Item", meta = (DisplayName = "On Dock Item Initialized"))
	void BP_OnItemInitialized(const FDockScrollItemData& Data, int32 Index);

	UFUNCTION(BlueprintImplementableEvent, Category = "Dock Item", meta = (DisplayName = "On Dock Item Focus Changed"))
	void BP_OnFocusChanged(bool bIsCurrent, float Scale);

	UPROPERTY(BlueprintReadOnly, meta = (BindWidgetOptional), Category = "Dock Item")
	TObjectPtr<UButton> SelectButton;

	UPROPERTY(BlueprintReadOnly, meta = (BindWidgetOptional), Category = "Dock Item")
	TObjectPtr<UImage> ItemImage;

	UPROPERTY(BlueprintReadOnly, meta = (BindWidgetOptional), Category = "Dock Item")
	TObjectPtr<UTextBlock> ItemName;

	UPROPERTY(BlueprintReadOnly, meta = (BindWidgetOptional), Category = "Dock Item")
	TObjectPtr<UBorder> HighlightBorder;

private:
	void BuildDefaultWidgetTree();
	void ApplyVisualStyle();

	UFUNCTION()
	void HandleClicked();

	UFUNCTION()
	void HandleHovered();

	UFUNCTION()
	void HandleUnhovered();

	UPROPERTY(Transient)
	TObjectPtr<UDockScrollWidget> OwnerDock;

	UPROPERTY(Transient)
	FDockScrollItemData ItemData;

	int32 ItemIndex = INDEX_NONE;
	bool bWasCurrent = false;
	bool bIsHovered = false;
	bool bIsSelected = false;
	bool bCurrentState = false;
	float VisualAlpha = 0.0f;
	float TargetVisualAlpha = 0.0f;
};
